In [2]:
import requests

In [30]:
ak='QGoMxq0XcHA0rLFfKUnOCnLBmLdkGFCL'
address='北京市朝阳区'
headers = {
    'content-type': 'application/json; charset=utf-8',
}
url=f'https://api.map.baidu.com/geocoding/v3/?address={address}&output=json&ak={ak}&output=json'

In [31]:
r=requests.get(url)

In [8]:
import json
json.loads(r.content.decode())['result']['location'].values()

dict_values([116.47359433070983, 39.927827997807846])

In [11]:
def get_address(city):
    ak='QGoMxq0XcHA0rLFfKUnOCnLBmLdkGFCL'
    url=f'https://api.map.baidu.com/geocoding/v3/?address={city}&output=json&ak={ak}&output=json'
    r=requests.get(url)
    r=json.loads(r.content.decode())
    if r['status']==0:
        return [r['result']['location']['lng'],r['result']['location']['lat']]
    else:
        return False
r=get_address('呼家楼')
r

[116.47359433070983, 39.927827997807846]

In [9]:
r1=json.loads(r.content.decode())
r1

{'status': 0,
 'result': {'location': {'lng': 116.47359433070983, 'lat': 39.927827997807846},
  'precise': 0,
  'confidence': 25,
  'comprehension': 100,
  'level': '乡镇'}}

In [10]:
r1.status

AttributeError: 'dict' object has no attribute 'status'

In [259]:
df=pd.read_csv(r'E:\wangzhilin\QuantumGalaxy\server_new\blueprints\map\static\委员信息表地图用_履历_表格视图 1.csv',)
df.columns=['name','year','sheng','shi','qu','story','other']

df

,name,year,sheng,shi,qu,story,other
0,习近平,1953,陕西省,渭南市,富平县,出生,NaN
1,习近平,1969,陕西省,延安市,延川县,陕西省延川县文安驿公社梁家河大队知青、党支部书记,NaN
2,习近平,1975,北京市,北京市,NaN,清华大学化工系基本有机合成专业学习,NaN
3,习近平,1979,北京市,北京市,NaN,国务院办公厅、中央军委办公厅秘书（现役）,NaN
4,习近平,1982,河北省,石家庄市,正定县,河北省正定县委副书记,NaN
...,...,...,...,...,...,...,...
192,蔡奇,2015,北京市,北京市,NaN,中央国家安全委员会办公室主持常务工作的副主任（正部长级）,NaN
193,蔡奇,2016,北京市,北京市,NaN,北京市委副书记、代市长、市长，北京2022年冬奥会和冬残奥会组织委员会执行主席、党组副书记,NaN
194,蔡奇,2017,北京市,北京市,NaN,北京市委书记，北京2022年冬奥会和冬残奥会组织委员会主席、党组书记,NaN
195,蔡奇,2017,北京市,北京市,NaN,中央政治局委员，北京市委书记，北京2022年冬奥会和冬残奥会组织委员会主席、党组书记,NaN
196,蔡奇,2022,北京市,北京市,NaN,中央政治局常委、中央书记处书记，北京市委书记，北京2022年冬奥会和冬残奥会组织委员会主席、...,NaN

In [271]:
import pandas as pd
import numpy as np
df=pd.read_csv(r'E:\wangzhilin\QuantumGalaxy\server_new\blueprints\map\static\委员信息表地图用_履历_表格视图 1.csv',)
df.columns=['name','year','sheng','shi','qu','story','other']
df = df.replace({np.nan: None})
df.sheng.replace({None:''},inplace=True)
df.shi.replace({None:''},inplace=True)
df.qu.replace({None:''},inplace=True)
df['city']=df.sheng+df.shi+df.qu
df.drop(['sheng','shi','qu'],axis=1,inplace=True)
df.year=df.year.astype('int')
df['story_start_in']=df['year']
df=df[['name','year','city','story','story_start_in','other']]
#df=df.where(df.notnull(),None,)

df = df.replace({np.nan: None})

df

,name,year,city,story,story_start_in,other
0,习近平,1953,陕西省渭南市富平县,出生,1953,None
1,习近平,1969,陕西省延安市延川县,陕西省延川县文安驿公社梁家河大队知青、党支部书记,1969,None
2,习近平,1975,北京市北京市,清华大学化工系基本有机合成专业学习,1975,None
3,习近平,1979,北京市北京市,国务院办公厅、中央军委办公厅秘书（现役）,1979,None
4,习近平,1982,河北省石家庄市正定县,河北省正定县委副书记,1982,None
...,...,...,...,...,...,...
193,蔡奇,2015,北京市北京市,中央国家安全委员会办公室主持常务工作的副主任（正部长级）,2015,None
194,蔡奇,2016,北京市北京市,北京市委副书记、代市长、市长，北京2022年冬奥会和冬残奥会组织委员会执行主席、党组副书记,2016,None
195,蔡奇,2017,北京市北京市,北京市委书记，北京2022年冬奥会和冬残奥会组织委员会主席、党组书记,2017,None
196,蔡奇,2017,北京市北京市,中央政治局委员，北京市委书记，北京2022年冬奥会和冬残奥会组织委员会主席、党组书记,2017,None
197,蔡奇,2022,北京市北京市,中央政治局常委、中央书记处书记，北京市委书记，北京2022年冬奥会和冬残奥会组织委员会主席、...,2022,None

In [272]:
years=df.year.sort_values().to_list()
start_year,end_year=years[0],years[-1]
yearslist=[]
for i in range(end_year-start_year+1):
    yearslist.append(start_year+i)
yearslist
new_df=pd.DataFrame(data=yearslist,columns=['year'])

In [273]:
persondf=new_df.merge(persondf,on='year',how='outer')
persondf

    year name    city                story  story_start_in other
0   1953  NaN     NaN                  NaN             NaN   NaN
1   1954  NaN     NaN                  NaN             NaN   NaN
2   1955  NaN     NaN                  NaN             NaN   NaN
3   1956  NaN     NaN                  NaN             NaN   NaN
4   1957  赵乐际  陕西省西安市                   出生          1957.0   NaN
..   ...  ...     ...                  ...             ...   ...
69  2018  赵乐际  北京市北京市  中央政治局常委，中央纪律检查委员会书记          2017.0   NaN
70  2019  赵乐际  北京市北京市  中央政治局常委，中央纪律检查委员会书记          2017.0   NaN
71  2020  赵乐际  北京市北京市  中央政治局常委，中央纪律检查委员会书记          2017.0   NaN
72  2021  赵乐际  北京市北京市  中央政治局常委，中央纪律检查委员会书记          2017.0   NaN
73  2022  赵乐际  北京市北京市              中央政治局常委          2022.0   NaN

[74 rows x 6 columns]

In [274]:
final_df=pd.DataFrame(columns=['name','year','city','story','story_start_in','other'])
for person,persondf in df.groupby('name'):
    persondf=new_df.merge(persondf,on='year',how='outer')
    
    persondf['name']=person
    persondf.sort_values('year',inplace=True)
    persondf['city'].fillna(method='pad',inplace=True)
    persondf['story'].fillna(method='pad',inplace=True)
    persondf['story_start_in'].fillna(method='pad',inplace=True)
    persondf.dropna(axis=0,subset='story',inplace=True)
    final_df=pd.concat([final_df,persondf],axis=0)
    


final_df.sort_values('year',inplace=True)
final_df['story_start_in']=final_df.story_start_in.astype('int')

In [275]:

final_df

,name,year,city,story,story_start_in,other
0,习近平,1953,陕西省渭南市富平县,出生,1953,None
1,习近平,1954,陕西省渭南市富平县,出生,1953,None
2,习近平,1955,陕西省渭南市富平县,出生,1953,None
2,蔡奇,1955,福建省三明市尤溪县,出生,1955,None
2,王沪宁,1955,山东省烟台市莱州市,出生,1955,None
...,...,...,...,...,...,...
72,习近平,2022,北京市北京市,中央委员会总书记，中共中央军事委员会主席，中华人民共和国主席，中华人民共和国中央军事委员会主席,2013,None
69,王沪宁,2022,北京市北京市,中央政治局常委，中央全面深化改革委员会办公室主任,2022,None
82,李强,2022,北京市北京市,中央政治局常委,2022,None
74,李希,2022,广东省广州市,中央政治局常委，中央纪律检查委员会书记，广东省委书记,2022,None
73,赵乐际,2022,北京市北京市,中央政治局常委,2022,None

In [278]:
dataset_p=[]
for year,yeardata in final_df.groupby('year'):
    data={'source':None}
    source=[]
    #oneyear
    #print(yeardata)
    yeardata=yeardata.sort_values('name')
    for i,r in yeardata.iterrows():
        #print(r)
        coord=get_address(r.city)
        if coord:
            lng,lat=coord
            source.append([lng,lat,r['name'],r.city,r.story,r.year,r.story_start_in])
    data['source']=source
    dataset_p.append(data)
    
dataset_p

[{'source': [[109.18643744727943,
    34.75726044025601,
    '习近平',
    '陕西省渭南市富平县',
    '出生',
    1953,
    1953]]},
 {'source': [[109.18643744727943,
    34.75726044025601,
    '习近平',
    '陕西省渭南市富平县',
    '出生',
    1954,
    1953]]},
 {'source': [[109.18643744727943,
    34.75726044025601,
    '习近平',
    '陕西省渭南市富平县',
    '出生',
    1955,
    1953],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1955,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1955,
    1955]]},
 {'source': [[109.18643744727943,
    34.75726044025601,
    '习近平',
    '陕西省渭南市富平县',
    '出生',
    1956,
    1953],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1956,
    1956],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1956,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1956,
    1955]]},
 {'source': [[109.18643744727943,
    34.75726044025601,
    '习近平',
    '陕西省渭南市富平县',
    '出生',
    1957,
    1953],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1957,
    1956],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1957,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1957,
    1955],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1957,
    1957]]},
 {'source': [[109.18643744727943,
    34.75726044025601,
    '习近平',
    '陕西省渭南市富平县',
    '出生',
    1958,
    1953],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1958,
    1956],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1958,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1958,
    1955],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1958,
    1957]]},
 {'source': [[109.18643744727943,
    34.75726044025601,
    '习近平',
    '陕西省渭南市富平县',
    '出生',
    1959,
    1953],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1959,
    1956],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1959,
    1959],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1959,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1959,
    1955],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1959,
    1957]]},
 {'source': [[109.18643744727943,
    34.75726044025601,
    '习近平',
    '陕西省渭南市富平县',
    '出生',
    1960,
    1953],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1960,
    1956],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1960,
    1959],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1960,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1960,
    1955],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1960,
    1957]]},
 {'source': [[109.18643744727943,
    34.75726044025601,
    '习近平',
    '陕西省渭南市富平县',
    '出生',
    1961,
    1953],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1961,
    1956],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1961,
    1959],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1961,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1961,
    1955],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1961,
    1957]]},
 {'source': [[120.90159173866185,
    31.98654943120089,
    '丁薛祥',
    '江苏省南通市',
    '出生',
    1962,
    1962],
   [109.18643744727943,
    34.75726044025601,
    '习近平',
    '陕西省渭南市富平县',
    '出生',
    1962,
    1953],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1962,
    1956],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1962,
    1959],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1962,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1962,
    1955],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1962,
    1957]]},
 {'source': [[120.90159173866185,
    31.98654943120089,
    '丁薛祥',
    '江苏省南通市',
    '出生',
    1963,
    1962],
   [109.18643744727943,
    34.75726044025601,
    '习近平',
    '陕西省渭南市富平县',
    '出生',
    1963,
    1953],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1963,
    1956],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1963,
    1959],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1963,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1963,
    1955],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1963,
    1957]]},
 {'source': [[120.90159173866185,
    31.98654943120089,
    '丁薛祥',
    '江苏省南通市',
    '出生',
    1964,
    1962],
   [109.18643744727943,
    34.75726044025601,
    '习近平',
    '陕西省渭南市富平县',
    '出生',
    1964,
    1953],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1964,
    1956],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1964,
    1959],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1964,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1964,
    1955],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1964,
    1957]]},
 {'source': [[120.90159173866185,
    31.98654943120089,
    '丁薛祥',
    '江苏省南通市',
    '出生',
    1965,
    1962],
   [109.18643744727943,
    34.75726044025601,
    '习近平',
    '陕西省渭南市富平县',
    '出生',
    1965,
    1953],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1965,
    1956],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1965,
    1959],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1965,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1965,
    1955],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1965,
    1957]]},
 {'source': [[120.90159173866185,
    31.98654943120089,
    '丁薛祥',
    '江苏省南通市',
    '出生',
    1966,
    1962],
   [109.18643744727943,
    34.75726044025601,
    '习近平',
    '陕西省渭南市富平县',
    '出生',
    1966,
    1953],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1966,
    1956],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1966,
    1959],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1966,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1966,
    1955],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1966,
    1957]]},
 {'source': [[120.90159173866185,
    31.98654943120089,
    '丁薛祥',
    '江苏省南通市',
    '出生',
    1967,
    1962],
   [109.18643744727943,
    34.75726044025601,
    '习近平',
    '陕西省渭南市富平县',
    '出生',
    1967,
    1953],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1967,
    1956],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1967,
    1959],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1967,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1967,
    1955],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1967,
    1957]]},
 {'source': [[120.90159173866185,
    31.98654943120089,
    '丁薛祥',
    '江苏省南通市',
    '出生',
    1968,
    1962],
   [109.18643744727943,
    34.75726044025601,
    '习近平',
    '陕西省渭南市富平县',
    '出生',
    1968,
    1953],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1968,
    1956],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1968,
    1959],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1968,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1968,
    1955],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1968,
    1957]]},
 {'source': [[120.90159173866185,
    31.98654943120089,
    '丁薛祥',
    '江苏省南通市',
    '出生',
    1969,
    1962],
   [110.20054028664882,
    36.884136960992926,
    '习近平',
    '陕西省延安市延川县',
    '陕西省延川县文安驿公社梁家河大队知青、党支部书记',
    1969,
    1969],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1969,
    1956],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1969,
    1959],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1969,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1969,
    1955],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1969,
    1957]]},
 {'source': [[120.90159173866185,
    31.98654943120089,
    '丁薛祥',
    '江苏省南通市',
    '出生',
    1970,
    1962],
   [110.20054028664882,
    36.884136960992926,
    '习近平',
    '陕西省延安市延川县',
    '陕西省延川县文安驿公社梁家河大队知青、党支部书记',
    1970,
    1969],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1970,
    1956],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1970,
    1959],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1970,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1970,
    1955],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1970,
    1957]]},
 {'source': [[120.90159173866185,
    31.98654943120089,
    '丁薛祥',
    '江苏省南通市',
    '出生',
    1971,
    1962],
   [110.20054028664882,
    36.884136960992926,
    '习近平',
    '陕西省延安市延川县',
    '陕西省延川县文安驿公社梁家河大队知青、党支部书记',
    1971,
    1969],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1971,
    1956],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1971,
    1959],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1971,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1971,
    1955],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1971,
    1957]]},
 {'source': [[120.90159173866185,
    31.98654943120089,
    '丁薛祥',
    '江苏省南通市',
    '出生',
    1972,
    1962],
   [110.20054028664882,
    36.884136960992926,
    '习近平',
    '陕西省延安市延川县',
    '陕西省延川县文安驿公社梁家河大队知青、党支部书记',
    1972,
    1969],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1972,
    1956],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1972,
    1959],
   [121.48053886017651,
    31.235929042252014,
    '王沪宁',
    '上海市上海市',
    '上海师范大学干校外语培训班学习',
    1972,
    1972],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1972,
    1955],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1972,
    1957]]},
 {'source': [[120.90159173866185,
    31.98654943120089,
    '丁薛祥',
    '江苏省南通市',
    '出生',
    1973,
    1962],
   [110.20054028664882,
    36.884136960992926,
    '习近平',
    '陕西省延安市延川县',
    '陕西省延川县文安驿公社梁家河大队知青、党支部书记',
    1973,
    1969],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1973,
    1956],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1973,
    1959],
   [121.48053886017651,
    31.235929042252014,
    '王沪宁',
    '上海市上海市',
    '上海师范大学干校外语培训班学习',
    1973,
    1972],
   [117.37144258732353,
    25.948143989823954,
    '蔡奇',
    '福建省三明市永安县',
    '福建省永安县西洋公社插队知青',
    1973,
    1973],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1973,
    1957]]},
 {'source': [[120.90159173866185,
    31.98654943120089,
    '丁薛祥',
    '江苏省南通市',
    '出生',
    1974,
    1962],
   [110.20054028664882,
    36.884136960992926,
    '习近平',
    '陕西省延安市延川县',
    '陕西省延川县文安驿公社梁家河大队知青、党支部书记',
    1974,
    1969],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1974,
    1956],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1974,
    1959],
   [121.48053886017651,
    31.235929042252014,
    '王沪宁',
    '上海市上海市',
    '上海师范大学干校外语培训班学习',
    1974,
    1972],
   [117.37144258732353,
    25.948143989823954,
    '蔡奇',
    '福建省三明市永安县',
    '福建省永安县西洋公社插队知青',
    1974,
    1973],
   [101.43953310384482,
    36.046158080751304,
    '赵乐际',
    '青海省海南藏族自治州贵德县',
    '青海省贵德县河东乡贡巴大队知青',
    1974,
    1974]]},
 {'source': [[120.90159173866185,
    31.98654943120089,
    '丁薛祥',
    '江苏省南通市',
    '出生',
    1975,
    1962],
   [116.4133836971231,
    39.910924547299565,
    '习近平',
    '北京市北京市',
    '清华大学化工系基本有机合成专业学习',
    1975,
    1975],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '甘肃省两当县云屏公社知青',
    1975,
    1975],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1975,
    1959],
   [121.48053886017651,
    31.235929042252014,
    '王沪宁',
    '上海市上海市',
    '上海师范大学干校外语培训班学习',
    1975,
    1972],
   [119.30346983854001,
    26.080429420698078,
    '蔡奇',
    '福建省福州市',
    '福建师范大学政教系政教专业学习',
    1975,
    1975],
   [101.78445017050855,
    36.62338469651661,
    '赵乐际',
    '青海省西宁市',
    '青海省商业厅通讯员',
    1975,
    1975]]},
 {'source': [[120.90159173866185,
    31.98654943120089,
    '丁薛祥',
    '江苏省南通市',
    '出生',
    1976,
    1962],
   [116.4133836971231,
    39.910924547299565,
    '习近平',
    '北京市北京市',
    '清华大学化工系基本有机合成专业学习',
    1976,
    1975],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '甘肃省两当县文教局、县委办公室干事',
    1976,
    1976],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '浙江省瑞安县马屿区机电排灌站职工',
    1976,
    1976],
   [121.48053886017651,
    31.235929042252014,
    '王沪宁',
    '上海市上海市',
    '上海师范大学干校外语培训班学习',
    1976,
    1972],
   [119.30346983854001,
    26.080429420698078,
    '蔡奇',
    '福建省福州市',
    '福建师范大学政教系政教专业学习',
    1976,
    1975],
   [101.78445017050855,
    36.62338469651661,
    '赵乐际',
    '青海省西宁市',
    '青海省商业厅通讯员',
    1976,
    1975]]},
 {'source': [[120.90159173866185,
    31.98654943120089,
    '丁薛祥',
    '江苏省南通市',
    '出生',
    1977,
    1962],
   [116.4133836971231,
    39.910924547299565,
    '习近平',
    '北京市北京市',
    '清华大学化工系基本有机合成专业学习',
    1977,
    1975],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '甘肃省两当县文教局、县委办公室干事',
    1977,
    1976],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '浙江省瑞安县工具三厂职工',
    1977,
    1977],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '借调瑞安县路线教育工作队驻江溪公社分队工作',
    1977,
    1977],
   [121.48053886017651,
    31.235929042252014,
    '王沪宁',
    '上海市上海市',
    '上海市出版局干部',
    1977,
    1977],
   [119.30346983854001,
    26.080429420698078,
    '蔡奇',
    '福建省福州市',
    '福建师范大学政教系政教专业学习',
    1977,
    1975],
   [116.4133836971231,
    39.910924547299565,
    '赵乐际',
    '北京市北京市',
    '北京大学哲学系哲学专业学习',
    1977,
    1977]]},
 {'source': [[123.92457086841536,
    47.3599771860153,
    '丁薛祥',
    '黑龙江省齐齐哈尔市',
    '东北重型机械学院机械工程系锻压工艺及设备专业学习',
    1978,
    1978],
   [116.4133836971231,
    39.910924547299565,
    '习近平',
    '北京市北京市',
    '清华大学化工系基本有机合成专业学习',
    1978,
    1975],
   [103.84052119633628,
    36.067234693545565,
    '李希',
    '甘肃省兰州市',
    '西北师范学院中文系汉语言文学专业学习',
    1978,
    1978],
   [121.63084278185603,
    29.866068124069646,
    '李强',
    '浙江省宁波市',
    '浙江农业大学宁波分校农机系农机化专业学习',
    1978,
    1978],
   [121.48053886017651,
    31.235929042252014,
    '王沪宁',
    '上海市上海市',
    '复旦大学国际政治系国际政治专业硕士研究生',
    1978,
    1978],
   [119.30346983854001,
    26.080429420698078,
    '蔡奇',
    '福建省福州市',
    '福建师范大学党委办公室干部',
    1978,
    1978],
   [116.4133836971231,
    39.910924547299565,
    '赵乐际',
    '北京市北京市',
    '北京大学哲学系哲学专业学习',
    1978,
    1977]]},
 {'source': [[123.92457086841536,
    47.3599771860153,
    '丁薛祥',
    '黑龙江省齐齐哈尔市',
    '东北重型机械学院机械工程系锻压工艺及设备专业学习',
    1979,
    1978],
   [116.4133836971231,
    39.910924547299565,
    '习近平',
    '北京市北京市',
    '国务院办公厅、中央军委办公厅秘书（现役）',
    1979,
    1979],
   [103.84052119633628,
    36.067234693545565,
    '李希',
    '甘肃省兰州市',
    '西北师范学院中文系汉语言文学专业学习',
    1979,
    1978],
   [121.63084278185603,
    29.866068124069646,
    '李强',
    '浙江省宁波市',
    '浙江农业大学宁波分校农机系农机化专业学习',
    1979,
    1978],
   [121.48053886017651,
    31.235929042252014,
    '王沪宁',
    '上海市上海市',
    '复旦大学国际政治系国际政治专业硕士研究生',
    1979,
    1978],
   [119.30346983854001,
    26.080429420698078,
    '蔡奇',
    '福建省福州市',
    '福建师范大学党委办公室干部',
    1979,
    1978],
   [116.4133836971231,
    39.910924547299565,
    '赵乐际',
    '北京市北京市',
    '北京大学哲学系哲学专业学习',
    1979,
    1977]]},
 {'source': [[123.92457086841536,
    47.3599771860153,
    '丁薛祥',
    '黑龙江省齐齐哈尔市',
    '东北重型机械学院机械工程系锻压工艺及设备专业学习',
    1980,
    1978],
   [116.4133836971231,
    39.910924547299565,
    '习近平',
    '北京市北京市',
    '国务院办公厅、中央军委办公厅秘书（现役）',
    1980,
    1979],
   [103.84052119633628,
    36.067234693545565,
    '李希',
    '甘肃省兰州市',
    '西北师范学院中文系汉语言文学专业学习',
    1980,
    1978],
   [121.63084278185603,
    29.866068124069646,
    '李强',
    '浙江省宁波市',
    '浙江农业大学宁波分校农机系农机化专业学习',
    1980,
    1978],
   [121.48053886017651,
    31.235929042252014,
    '王沪宁',
    '上海市上海市',
    '复旦大学国际政治系国际政治专业硕士研究生',
    1980,
    1978],
   [119.30346983854001,
    26.080429420698078,
    '蔡奇',
    '福建省福州市',
    '福建师范大学党委办公室干部',
    1980,
    1978],
   [101.78445017050855,
    36.62338469651661,
    '赵乐际',
    '青海省西宁市',
    '青海省商业厅政治处干事，省商业学校教师、校团委书记',
    1980,
    1980]]},
 {'source': [[123.92457086841536,
    47.3599771860153,
    '丁薛祥',
    '黑龙江省齐齐哈尔市',
    '东北重型机械学院机械工程系锻压工艺及设备专业学习',
    1981,
    1978],
   [116.4133836971231,
    39.910924547299565,
    '习近平',
    '北京市北京市',
    '国务院办公厅、中央军委办公厅秘书（现役）',
    1981,
    1979],
   [103.84052119633628,
    36.067234693545565,
    '李希',
    '甘肃省兰州市',
    '西北师范学院中文系汉语言文学专业学习',
    1981,
    1978],
   [121.63084278185603,
    29.866068124069646,
    '李强',
    '浙江省宁波市',
    '浙江农业大学宁波分校农机系农机化专业学习',
    1981,
    1978],
   [121.48053886017651,
    31.235929042252014,
    '王沪宁',
    '上海市上海市',
    '复旦大学国际政治系教师、副教授、教授',
    1981,
    1981],
   [119.30346983854001,
    26.080429420698078,
    '蔡奇',
    '福建省福州市',
    '福建师范大学党委办公室干部',
    1981,
    1978],
   [101.78445017050855,
    36.62338469651661,
    '赵乐际',
    '青海省西宁市',
    '青海省商业厅政治处干事，省商业学校教师、校团委书记',
    1981,
    1980]]},
 {'source': [[121.48053886017651,
    31.235929042252014,
    '丁薛祥',
    '上海市上海市',

In [279]:
js=json.dumps(dataset_p)
f2 = open(r'E:\wangzhilin\QuantumGalaxy\server_new\blueprints\map\static\js.json', 'w')
f2.write(js)
f2.close()

In [280]:
f=open(r'E:\wangzhilin\QuantumGalaxy\server_new\blueprints\map\static\js.json', 'r')
content = f.read()
a = json.loads(content)
a

[{'source': [[109.18643744727943,
    34.75726044025601,
    '习近平',
    '陕西省渭南市富平县',
    '出生',
    1953,
    1953]]},
 {'source': [[109.18643744727943,
    34.75726044025601,
    '习近平',
    '陕西省渭南市富平县',
    '出生',
    1954,
    1953]]},
 {'source': [[109.18643744727943,
    34.75726044025601,
    '习近平',
    '陕西省渭南市富平县',
    '出生',
    1955,
    1953],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1955,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1955,
    1955]]},
 {'source': [[109.18643744727943,
    34.75726044025601,
    '习近平',
    '陕西省渭南市富平县',
    '出生',
    1956,
    1953],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1956,
    1956],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1956,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1956,
    1955]]},
 {'source': [[109.18643744727943,
    34.75726044025601,
    '习近平',
    '陕西省渭南市富平县',
    '出生',
    1957,
    1953],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1957,
    1956],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1957,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1957,
    1955],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1957,
    1957]]},
 {'source': [[109.18643744727943,
    34.75726044025601,
    '习近平',
    '陕西省渭南市富平县',
    '出生',
    1958,
    1953],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1958,
    1956],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1958,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1958,
    1955],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1958,
    1957]]},
 {'source': [[109.18643744727943,
    34.75726044025601,
    '习近平',
    '陕西省渭南市富平县',
    '出生',
    1959,
    1953],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1959,
    1956],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1959,
    1959],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1959,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1959,
    1955],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1959,
    1957]]},
 {'source': [[109.18643744727943,
    34.75726044025601,
    '习近平',
    '陕西省渭南市富平县',
    '出生',
    1960,
    1953],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1960,
    1956],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1960,
    1959],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1960,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1960,
    1955],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1960,
    1957]]},
 {'source': [[109.18643744727943,
    34.75726044025601,
    '习近平',
    '陕西省渭南市富平县',
    '出生',
    1961,
    1953],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1961,
    1956],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1961,
    1959],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1961,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1961,
    1955],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1961,
    1957]]},
 {'source': [[120.90159173866185,
    31.98654943120089,
    '丁薛祥',
    '江苏省南通市',
    '出生',
    1962,
    1962],
   [109.18643744727943,
    34.75726044025601,
    '习近平',
    '陕西省渭南市富平县',
    '出生',
    1962,
    1953],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1962,
    1956],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1962,
    1959],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1962,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1962,
    1955],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1962,
    1957]]},
 {'source': [[120.90159173866185,
    31.98654943120089,
    '丁薛祥',
    '江苏省南通市',
    '出生',
    1963,
    1962],
   [109.18643744727943,
    34.75726044025601,
    '习近平',
    '陕西省渭南市富平县',
    '出生',
    1963,
    1953],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1963,
    1956],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1963,
    1959],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1963,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1963,
    1955],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1963,
    1957]]},
 {'source': [[120.90159173866185,
    31.98654943120089,
    '丁薛祥',
    '江苏省南通市',
    '出生',
    1964,
    1962],
   [109.18643744727943,
    34.75726044025601,
    '习近平',
    '陕西省渭南市富平县',
    '出生',
    1964,
    1953],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1964,
    1956],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1964,
    1959],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1964,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1964,
    1955],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1964,
    1957]]},
 {'source': [[120.90159173866185,
    31.98654943120089,
    '丁薛祥',
    '江苏省南通市',
    '出生',
    1965,
    1962],
   [109.18643744727943,
    34.75726044025601,
    '习近平',
    '陕西省渭南市富平县',
    '出生',
    1965,
    1953],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1965,
    1956],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1965,
    1959],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1965,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1965,
    1955],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1965,
    1957]]},
 {'source': [[120.90159173866185,
    31.98654943120089,
    '丁薛祥',
    '江苏省南通市',
    '出生',
    1966,
    1962],
   [109.18643744727943,
    34.75726044025601,
    '习近平',
    '陕西省渭南市富平县',
    '出生',
    1966,
    1953],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1966,
    1956],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1966,
    1959],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1966,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1966,
    1955],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1966,
    1957]]},
 {'source': [[120.90159173866185,
    31.98654943120089,
    '丁薛祥',
    '江苏省南通市',
    '出生',
    1967,
    1962],
   [109.18643744727943,
    34.75726044025601,
    '习近平',
    '陕西省渭南市富平县',
    '出生',
    1967,
    1953],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1967,
    1956],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1967,
    1959],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1967,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1967,
    1955],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1967,
    1957]]},
 {'source': [[120.90159173866185,
    31.98654943120089,
    '丁薛祥',
    '江苏省南通市',
    '出生',
    1968,
    1962],
   [109.18643744727943,
    34.75726044025601,
    '习近平',
    '陕西省渭南市富平县',
    '出生',
    1968,
    1953],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1968,
    1956],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1968,
    1959],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1968,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1968,
    1955],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1968,
    1957]]},
 {'source': [[120.90159173866185,
    31.98654943120089,
    '丁薛祥',
    '江苏省南通市',
    '出生',
    1969,
    1962],
   [110.20054028664882,
    36.884136960992926,
    '习近平',
    '陕西省延安市延川县',
    '陕西省延川县文安驿公社梁家河大队知青、党支部书记',
    1969,
    1969],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1969,
    1956],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1969,
    1959],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1969,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1969,
    1955],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1969,
    1957]]},
 {'source': [[120.90159173866185,
    31.98654943120089,
    '丁薛祥',
    '江苏省南通市',
    '出生',
    1970,
    1962],
   [110.20054028664882,
    36.884136960992926,
    '习近平',
    '陕西省延安市延川县',
    '陕西省延川县文安驿公社梁家河大队知青、党支部书记',
    1970,
    1969],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1970,
    1956],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1970,
    1959],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1970,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1970,
    1955],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1970,
    1957]]},
 {'source': [[120.90159173866185,
    31.98654943120089,
    '丁薛祥',
    '江苏省南通市',
    '出生',
    1971,
    1962],
   [110.20054028664882,
    36.884136960992926,
    '习近平',
    '陕西省延安市延川县',
    '陕西省延川县文安驿公社梁家河大队知青、党支部书记',
    1971,
    1969],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1971,
    1956],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1971,
    1959],
   [119.94859307736998,
    37.18263660907421,
    '王沪宁',
    '山东省烟台市莱州市',
    '出生',
    1971,
    1955],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1971,
    1955],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1971,
    1957]]},
 {'source': [[120.90159173866185,
    31.98654943120089,
    '丁薛祥',
    '江苏省南通市',
    '出生',
    1972,
    1962],
   [110.20054028664882,
    36.884136960992926,
    '习近平',
    '陕西省延安市延川县',
    '陕西省延川县文安驿公社梁家河大队知青、党支部书记',
    1972,
    1969],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1972,
    1956],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1972,
    1959],
   [121.48053886017651,
    31.235929042252014,
    '王沪宁',
    '上海市上海市',
    '上海师范大学干校外语培训班学习',
    1972,
    1972],
   [118.19743971364737,
    26.176218039460192,
    '蔡奇',
    '福建省三明市尤溪县',
    '出生',
    1972,
    1955],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1972,
    1957]]},
 {'source': [[120.90159173866185,
    31.98654943120089,
    '丁薛祥',
    '江苏省南通市',
    '出生',
    1973,
    1962],
   [110.20054028664882,
    36.884136960992926,
    '习近平',
    '陕西省延安市延川县',
    '陕西省延川县文安驿公社梁家河大队知青、党支部书记',
    1973,
    1969],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1973,
    1956],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1973,
    1959],
   [121.48053886017651,
    31.235929042252014,
    '王沪宁',
    '上海市上海市',
    '上海师范大学干校外语培训班学习',
    1973,
    1972],
   [117.37144258732353,
    25.948143989823954,
    '蔡奇',
    '福建省三明市永安县',
    '福建省永安县西洋公社插队知青',
    1973,
    1973],
   [108.94646555063274,
    34.34726881662395,
    '赵乐际',
    '陕西省西安市',
    '出生',
    1973,
    1957]]},
 {'source': [[120.90159173866185,
    31.98654943120089,
    '丁薛祥',
    '江苏省南通市',
    '出生',
    1974,
    1962],
   [110.20054028664882,
    36.884136960992926,
    '习近平',
    '陕西省延安市延川县',
    '陕西省延川县文安驿公社梁家河大队知青、党支部书记',
    1974,
    1969],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '出生',
    1974,
    1956],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1974,
    1959],
   [121.48053886017651,
    31.235929042252014,
    '王沪宁',
    '上海市上海市',
    '上海师范大学干校外语培训班学习',
    1974,
    1972],
   [117.37144258732353,
    25.948143989823954,
    '蔡奇',
    '福建省三明市永安县',
    '福建省永安县西洋公社插队知青',
    1974,
    1973],
   [101.43953310384482,
    36.046158080751304,
    '赵乐际',
    '青海省海南藏族自治州贵德县',
    '青海省贵德县河东乡贡巴大队知青',
    1974,
    1974]]},
 {'source': [[120.90159173866185,
    31.98654943120089,
    '丁薛祥',
    '江苏省南通市',
    '出生',
    1975,
    1962],
   [116.4133836971231,
    39.910924547299565,
    '习近平',
    '北京市北京市',
    '清华大学化工系基本有机合成专业学习',
    1975,
    1975],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '甘肃省两当县云屏公社知青',
    1975,
    1975],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '出生',
    1975,
    1959],
   [121.48053886017651,
    31.235929042252014,
    '王沪宁',
    '上海市上海市',
    '上海师范大学干校外语培训班学习',
    1975,
    1972],
   [119.30346983854001,
    26.080429420698078,
    '蔡奇',
    '福建省福州市',
    '福建师范大学政教系政教专业学习',
    1975,
    1975],
   [101.78445017050855,
    36.62338469651661,
    '赵乐际',
    '青海省西宁市',
    '青海省商业厅通讯员',
    1975,
    1975]]},
 {'source': [[120.90159173866185,
    31.98654943120089,
    '丁薛祥',
    '江苏省南通市',
    '出生',
    1976,
    1962],
   [116.4133836971231,
    39.910924547299565,
    '习近平',
    '北京市北京市',
    '清华大学化工系基本有机合成专业学习',
    1976,
    1975],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '甘肃省两当县文教局、县委办公室干事',
    1976,
    1976],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '浙江省瑞安县马屿区机电排灌站职工',
    1976,
    1976],
   [121.48053886017651,
    31.235929042252014,
    '王沪宁',
    '上海市上海市',
    '上海师范大学干校外语培训班学习',
    1976,
    1972],
   [119.30346983854001,
    26.080429420698078,
    '蔡奇',
    '福建省福州市',
    '福建师范大学政教系政教专业学习',
    1976,
    1975],
   [101.78445017050855,
    36.62338469651661,
    '赵乐际',
    '青海省西宁市',
    '青海省商业厅通讯员',
    1976,
    1975]]},
 {'source': [[120.90159173866185,
    31.98654943120089,
    '丁薛祥',
    '江苏省南通市',
    '出生',
    1977,
    1962],
   [116.4133836971231,
    39.910924547299565,
    '习近平',
    '北京市北京市',
    '清华大学化工系基本有机合成专业学习',
    1977,
    1975],
   [106.31141946598899,
    33.91512283517304,
    '李希',
    '甘肃省陇南市两当县',
    '甘肃省两当县文教局、县委办公室干事',
    1977,
    1976],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '浙江省瑞安县工具三厂职工',
    1977,
    1977],
   [120.66158218606775,
    27.783950736231652,
    '李强',
    '浙江省温州市瑞安县',
    '借调瑞安县路线教育工作队驻江溪公社分队工作',
    1977,
    1977],
   [121.48053886017651,
    31.235929042252014,
    '王沪宁',
    '上海市上海市',
    '上海市出版局干部',
    1977,
    1977],
   [119.30346983854001,
    26.080429420698078,
    '蔡奇',
    '福建省福州市',
    '福建师范大学政教系政教专业学习',
    1977,
    1975],
   [116.4133836971231,
    39.910924547299565,
    '赵乐际',
    '北京市北京市',
    '北京大学哲学系哲学专业学习',
    1977,
    1977]]},
 {'source': [[123.92457086841536,
    47.3599771860153,
    '丁薛祥',
    '黑龙江省齐齐哈尔市',
    '东北重型机械学院机械工程系锻压工艺及设备专业学习',
    1978,
    1978],
   [116.4133836971231,
    39.910924547299565,
    '习近平',
    '北京市北京市',
    '清华大学化工系基本有机合成专业学习',
    1978,
    1975],
   [103.84052119633628,
    36.067234693545565,
    '李希',
    '甘肃省兰州市',
    '西北师范学院中文系汉语言文学专业学习',
    1978,
    1978],
   [121.63084278185603,
    29.866068124069646,
    '李强',
    '浙江省宁波市',
    '浙江农业大学宁波分校农机系农机化专业学习',
    1978,
    1978],
   [121.48053886017651,
    31.235929042252014,
    '王沪宁',
    '上海市上海市',
    '复旦大学国际政治系国际政治专业硕士研究生',
    1978,
    1978],
   [119.30346983854001,
    26.080429420698078,
    '蔡奇',
    '福建省福州市',
    '福建师范大学党委办公室干部',
    1978,
    1978],
   [116.4133836971231,
    39.910924547299565,
    '赵乐际',
    '北京市北京市',
    '北京大学哲学系哲学专业学习',
    1978,
    1977]]},
 {'source': [[123.92457086841536,
    47.3599771860153,
    '丁薛祥',
    '黑龙江省齐齐哈尔市',
    '东北重型机械学院机械工程系锻压工艺及设备专业学习',
    1979,
    1978],
   [116.4133836971231,
    39.910924547299565,
    '习近平',
    '北京市北京市',
    '国务院办公厅、中央军委办公厅秘书（现役）',
    1979,
    1979],
   [103.84052119633628,
    36.067234693545565,
    '李希',
    '甘肃省兰州市',
    '西北师范学院中文系汉语言文学专业学习',
    1979,
    1978],
   [121.63084278185603,
    29.866068124069646,
    '李强',
    '浙江省宁波市',
    '浙江农业大学宁波分校农机系农机化专业学习',
    1979,
    1978],
   [121.48053886017651,
    31.235929042252014,
    '王沪宁',
    '上海市上海市',
    '复旦大学国际政治系国际政治专业硕士研究生',
    1979,
    1978],
   [119.30346983854001,
    26.080429420698078,
    '蔡奇',
    '福建省福州市',
    '福建师范大学党委办公室干部',
    1979,
    1978],
   [116.4133836971231,
    39.910924547299565,
    '赵乐际',
    '北京市北京市',
    '北京大学哲学系哲学专业学习',
    1979,
    1977]]},
 {'source': [[123.92457086841536,
    47.3599771860153,
    '丁薛祥',
    '黑龙江省齐齐哈尔市',
    '东北重型机械学院机械工程系锻压工艺及设备专业学习',
    1980,
    1978],
   [116.4133836971231,
    39.910924547299565,
    '习近平',
    '北京市北京市',
    '国务院办公厅、中央军委办公厅秘书（现役）',
    1980,
    1979],
   [103.84052119633628,
    36.067234693545565,
    '李希',
    '甘肃省兰州市',
    '西北师范学院中文系汉语言文学专业学习',
    1980,
    1978],
   [121.63084278185603,
    29.866068124069646,
    '李强',
    '浙江省宁波市',
    '浙江农业大学宁波分校农机系农机化专业学习',
    1980,
    1978],
   [121.48053886017651,
    31.235929042252014,
    '王沪宁',
    '上海市上海市',
    '复旦大学国际政治系国际政治专业硕士研究生',
    1980,
    1978],
   [119.30346983854001,
    26.080429420698078,
    '蔡奇',
    '福建省福州市',
    '福建师范大学党委办公室干部',
    1980,
    1978],
   [101.78445017050855,
    36.62338469651661,
    '赵乐际',
    '青海省西宁市',
    '青海省商业厅政治处干事，省商业学校教师、校团委书记',
    1980,
    1980]]},
 {'source': [[123.92457086841536,
    47.3599771860153,
    '丁薛祥',
    '黑龙江省齐齐哈尔市',
    '东北重型机械学院机械工程系锻压工艺及设备专业学习',
    1981,
    1978],
   [116.4133836971231,
    39.910924547299565,
    '习近平',
    '北京市北京市',
    '国务院办公厅、中央军委办公厅秘书（现役）',
    1981,
    1979],
   [103.84052119633628,
    36.067234693545565,
    '李希',
    '甘肃省兰州市',
    '西北师范学院中文系汉语言文学专业学习',
    1981,
    1978],
   [121.63084278185603,
    29.866068124069646,
    '李强',
    '浙江省宁波市',
    '浙江农业大学宁波分校农机系农机化专业学习',
    1981,
    1978],
   [121.48053886017651,
    31.235929042252014,
    '王沪宁',
    '上海市上海市',
    '复旦大学国际政治系教师、副教授、教授',
    1981,
    1981],
   [119.30346983854001,
    26.080429420698078,
    '蔡奇',
    '福建省福州市',
    '福建师范大学党委办公室干部',
    1981,
    1978],
   [101.78445017050855,
    36.62338469651661,
    '赵乐际',
    '青海省西宁市',
    '青海省商业厅政治处干事，省商业学校教师、校团委书记',
    1981,
    1980]]},
 {'source': [[121.48053886017651,
    31.235929042252014,
    '丁薛祥',
    '上海市上海市',

In [166]:
for num in l:
    if l.count(num)!=1:
        print(num,l.count(num))

1999 2
1999 2

In [230]:
final_df.to_csv(r'E:\wangzhilin\QuantumGalaxy\server_new\blueprints\map\static\1.csv')